import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-800">
        <header className=" text-white h-20 w-screen font-serif flex" >
          <h2 className="text-4xl ml-10 pt-3">Portfolio</h2>
          <nav className="inline-grid absolute right-8 top-6 gap-7 grid-cols-5 place-items-center">
            <a href="#home">Home</a>
            <a href="#about">About</a>
            <a href="#portfolio">Portfolio</a>
            <a href="#services">Services</a>
            <a href="#home">Contact</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
